export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT';
export const FETCH_WEATHER_REPORT_STARTED = 'FETCH_WEATHER_REPORT_STARTED';
export const FETCH_WEATHER_REPORT_SUCCESS = 'FETCH_WEATHER_REPORT_SUCCESS';
export const FETCH_WEATHER_REPORT_FAILED = 'FETCH_WEATHER_REPORT_FAILED';

